# Generated by Django 5.0.6 on 2024-05-27 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icecream_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IceCreams',
            new_name='IceCream',
        ),
        migrations.RenameModel(
            old_name='Testimonials',
            new_name='Testimonial',
        ),
    ]
