# Generated by Django 5.0.6 on 2024-05-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream_api', '0002_rename_icecreams_icecream_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='img',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
